allow-when-not-in-survival-mode: false
world-specific-backpacks: false
drop-items-on-player-death: true
disable-noitemdrop-perm: false
auto-add-pickups-to-storage: true
update-check: true
use-Minecraft-UUID: false
display-prefix: true
disable-drop-message: false
storage-name: Backpack
error-log-level: 1
Compatibility-Settings:
  Vanish-No-Packet:
    no-item-pickup-when-vanished: true
world-blacklist:
  worlds:
  - example_world
  - example_world2
blacklisted-items:
  items:
  - GRASS
  - BEDROCK
